services:
  - type: web
    name: enhanced-c2-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /api/health
    envVars:
      - key: C2_TOKEN
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY_B64 # Base64 encoded 32-byte key
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.6
